# src/config.py
"""Centralized configuration for the book recommender application."""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

# --- File and Directory Paths ---
# Base directory of the project
# Path structure: config.py -> core/ -> book_recommender/ -> src/ -> project_root/
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent

# Data directories
DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

# Data files
RAW_DATA_PATH = RAW_DATA_DIR / "books_prepared.csv"
PROCESSED_DATA_PATH = PROCESSED_DATA_DIR / "books_cleaned.parquet"
EMBEDDINGS_PATH = PROCESSED_DATA_DIR / "book_embeddings.npy"
EMBEDDING_METADATA_PATH = PROCESSED_DATA_DIR / "embedding_metadata.json"


# --- Model Configuration ---
# Name of the sentence-transformer model to use
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")

# Dimension of the embeddings generated by the model
EMBEDDING_DIMENSION = 384

EMBEDDING_DEVICE = os.getenv("EMBEDDING_DEVICE", "cpu")  # Options: 'cpu', 'cuda'
# Default batch size for encoding
DEFAULT_BATCH_SIZE = 32


# --- Recommender Configuration ---
# Default number of recommendations to return
DEFAULT_TOP_K = 10
MIN_SIMILARITY_THRESHOLD = 0.3
NUM_CLUSTERS = 20  # Number of clusters for K-Means clustering


# --- App Configuration ---
APP_VERSION = "0.1.0"
FALLBACK_COVER_URL = "https://placehold.co/200x300/667eea/white?text=No+Cover"


# --- Data/Model Versioning (Future Consideration)
# For production systems, consider implementing a robust data and model
# versioning system (e.g., DVC - Data Version Control) to track changes
# to processed data and generated embeddings. For this MVP, manual
# management or timestamping of files is suggested if versioning is critical.
