# src/config.py
"""Centralized configuration for the book recommender application."""

import os

# --- File and Directory Paths ---
# Base directory of the project
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Data directories
DATA_DIR = os.path.join(BASE_DIR, "data")
RAW_DATA_DIR = os.path.join(DATA_DIR, "raw")
PROCESSED_DATA_DIR = os.path.join(DATA_DIR, "processed")

# Data files
RAW_DATA_PATH = os.path.join(RAW_DATA_DIR, "books_prepared.csv")
PROCESSED_DATA_PATH = os.path.join(PROCESSED_DATA_DIR, "books_cleaned.parquet")
EMBEDDINGS_PATH = os.path.join(PROCESSED_DATA_DIR, "book_embeddings.npy")
EMBEDDING_METADATA_PATH = os.path.join(PROCESSED_DATA_DIR, "embedding_metadata.json")


# --- Model Configuration ---
# Name of the sentence-transformer model to use
EMBEDDING_MODEL = 'all-MiniLM-L6-v2'

# Dimension of the embeddings generated by the model
EMBEDDING_DIMENSION = 384

# Default batch size for encoding
DEFAULT_BATCH_SIZE = 32


# --- Recommender Configuration ---
# Default number of recommendations to return
DEFAULT_TOP_K = 10
MIN_SIMILARITY_THRESHOLD = 0.3


# --- App Configuration ---
APP_VERSION = "0.1.0"

# --- Data/Model Versioning (Future Consideration) ---
# For production systems, consider implementing a robust data and model
# versioning system (e.g., DVC - Data Version Control) to track changes
# to processed data and generated embeddings. For this MVP, manual
# management or timestamping of files is suggested if versioning is critical.

